// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl =
  process.env["DATABASE_HOST"] &&
  process.env["DATABASE_NAME"] &&
  process.env["DATABASE_USER"] &&
  process.env["DATABASE_PASSWORD"]
    ? `mysql://${encodeURIComponent(process.env["DATABASE_USER"])}:${encodeURIComponent(process.env["DATABASE_PASSWORD"])}@${process.env["DATABASE_HOST"]}:${process.env["DATABASE_PORT"] ?? "3306"}/${encodeURIComponent(process.env["DATABASE_NAME"])}?sslaccept=strict`
    : process.env["DATABASE_URL"];

export default defineConfig({
  schema: "src/prisma/schema.prisma",
  migrations: {
    path: "src/prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
